from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_report(
    filename,
    document,
    score,
    status,
    aadhaar,
    gender,
    dob,
    face_found,
    qr_found,
    aadhaar_valid,
    quality,
    ocr_score
):
    """
    Generate Verification Report PDF
    """

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>AI DOCUMENT VERIFICATION REPORT</b>", styles["Title"]))

    story.append(Paragraph(f"<b>Status:</b> {status}", styles["BodyText"]))
    story.append(Paragraph(f"<b>Authenticity Score:</b> {score}%", styles["BodyText"]))

    story.append(Paragraph("<br/><b>Document Information</b>", styles["Heading2"]))

    story.append(Paragraph(f"Document Type: {document}", styles["BodyText"]))
    story.append(Paragraph(f"Aadhaar Number: {aadhaar}", styles["BodyText"]))
    story.append(Paragraph(f"Gender: {gender}", styles["BodyText"]))
    story.append(Paragraph(f"Date of Birth: {dob}", styles["BodyText"]))

    story.append(Paragraph("<br/><b>Verification Checks</b>", styles["Heading2"]))

    story.append(Paragraph(f"Face Detected: {face_found}", styles["BodyText"]))
    story.append(Paragraph(f"QR Code Found: {qr_found}", styles["BodyText"]))
    story.append(Paragraph(f"Aadhaar Valid: {aadhaar_valid}", styles["BodyText"]))
    story.append(Paragraph(f"Image Quality: {quality}", styles["BodyText"]))
    story.append(Paragraph(f"OCR Quality: {ocr_score}", styles["BodyText"]))

    story.append(Paragraph("<br/>Generated By", styles["Heading2"]))
    story.append(Paragraph("AI Document Verification System", styles["BodyText"]))

    story.append(
        Paragraph(
            datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
            styles["BodyText"]
        )
    )

    pdf.build(story)